version: '3.8'

services:
  opanel:
    build: .
    container_name: opanel
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - opanel-data:/opt/opanel/db
      - opanel-config:/etc/opanel
      - opanel-mysql:/var/lib/mysql
    restart: unless-stopped

volumes:
  opanel-data:
  opanel-config:
  opanel-mysql:
