version: '3.8'

services:
  opanel:
    build: .
    container_name: opanel
    ports:
      - "8443:8443"
    volumes:
      - opanel-data:/opt/opanel/db
      - opanel-config:/etc/opanel
      - opanel-mysql:/var/lib/mysql
      - opanel-nginx:/etc/nginx/sites-enabled
    restart: unless-stopped

volumes:
  opanel-data:
  opanel-config:
  opanel-mysql:
  opanel-nginx:
