#!/bin/bash
set -e

echo "Starting OPanel services..."

# Start MariaDB
echo "Starting MariaDB..."
mkdir -p /var/run/mysqld
chown mysql:mysql /var/run/mysqld
# Initialize MariaDB data directory if needed
if [ ! -d /var/lib/mysql/mysql ]; then
    mysql_install_db --user=mysql --datadir=/var/lib/mysql
fi
mysqld_safe &
sleep 3

# Wait for MariaDB to be ready
for i in $(seq 1 30); do
    if mysqladmin ping --socket=/var/run/mysqld/mysqld.sock 2>/dev/null; then
        echo "MariaDB is ready"
        break
    fi
    sleep 1
done

# Create mail database and tables in MariaDB
echo "Initializing mail database..."
mysql --socket=/var/run/mysqld/mysqld.sock -u root <<'EOSQL'
CREATE DATABASE IF NOT EXISTS opanel_mail;
CREATE TABLE IF NOT EXISTS opanel_mail.virtual_domains (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opanel_mail.virtual_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain_id INT NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(512) NOT NULL,
    quota BIGINT DEFAULT 1073741824,
    enabled TINYINT DEFAULT 1,
    UNIQUE KEY uk_domain_user (domain_id, username),
    FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opanel_mail.virtual_aliases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain_id INT NOT NULL,
    source VARCHAR(255) NOT NULL,
    destination VARCHAR(512) NOT NULL,
    UNIQUE KEY uk_domain_source (domain_id, source),
    FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
) ENGINE=InnoDB;
GRANT ALL PRIVILEGES ON opanel_mail.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
EOSQL
echo "Mail database ready"

# Create vmail user/group
groupadd -g 5000 vmail 2>/dev/null || true
useradd -u 5000 -g vmail -d /var/vmail -s /usr/sbin/nologin vmail 2>/dev/null || true
mkdir -p /var/vmail
chown vmail:vmail /var/vmail
chmod 770 /var/vmail

# Configure Bind9
echo "Configuring Bind9..."
mkdir -p /etc/bind/zones
cat > /etc/bind/named.conf <<'EOBIND'
include "/etc/bind/named.conf.options";
include "/etc/bind/named.conf.local";
EOBIND

# Generate rndc key if not present
if [ ! -f /etc/bind/rndc.key ]; then
    rndc-confgen -a -b 512 2>/dev/null || true
fi

cat > /etc/bind/named.conf.options <<'EOBIND'
options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    recursion yes;
    dnssec-validation auto;
};
EOBIND

# Create empty local zones file
if [ ! -f /etc/bind/named.conf.local ]; then
    echo "// Auto-generated by OPanel" > /etc/bind/named.conf.local
fi

# Start Bind9
echo "Starting Bind9..."
named -g -u bind &
NAMED_PID=$!
sleep 2
# Wait for rndc to be ready
for i in $(seq 1 10); do
    if rndc status 2>/dev/null | grep -q "running"; then
        echo "Bind9 is ready"
        break
    fi
    sleep 1
done

# Configure Postfix
echo "Configuring Postfix..."
cat > /etc/postfix/main.cf <<'EOPF'
# Basic settings
myhostname = mail.localdomain
mydomain = localdomain
myorigin = $mydomain
mydestination = $myhostname, localhost.$mydomain, localhost
mynetworks = 127.0.0.0/8
inet_interfaces = all
inet_protocols = all

# Virtual domains
virtual_mailbox_domains = proxy:mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
virtual_mailbox_maps = proxy:mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
virtual_alias_maps = proxy:mysql:/etc/postfix/mysql-virtual-alias-maps.cf

# Mailbox delivery via Dovecot LMTP
virtual_transport = lmtp:unix:private/dovecot-lmtp

# Authentication
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/dovecot-auth
smtpd_sasl_security_options = noanonymous

# TLS
smtpd_tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_security_level = may
smtp_tls_security_level = may

# Restrictions
smtpd_helo_required = yes
smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname
smtpd_sender_restrictions = permit_mynetworks, reject_non_fqdn_sender, reject_unknown_sender_domain
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_non_fqdn_recipient, reject_unknown_recipient_domain

# Milter (Rspamd)
milter_protocol = 6
milter_default_action = accept
smtpd_milters = inet:localhost:11332
non_smtpd_milters = inet:localhost:11332

# Message size limit
message_size_limit = 52428800
EOPF

# Generate MySQL lookup configs for Postfix
cat > /etc/postfix/mysql-virtual-mailbox-domains.cf <<'EOSQL'
user = root
password =
hosts = unix:/var/run/mysqld/mysqld.sock
dbname = opanel_mail
query = SELECT name FROM virtual_domains WHERE name = '%s'
EOSQL

cat > /etc/postfix/mysql-virtual-mailbox-maps.cf <<'EOSQL'
user = root
password =
hosts = unix:/var/run/mysqld/mysqld.sock
dbname = opanel_mail
query = SELECT 1 FROM virtual_users vu JOIN virtual_domains vd ON vu.domain_id = vd.id WHERE CONCAT(vu.username, '@', vd.name) = '%s' AND vu.enabled = 1
EOSQL

cat > /etc/postfix/mysql-virtual-alias-maps.cf <<'EOSQL'
user = root
password =
hosts = unix:/var/run/mysqld/mysqld.sock
dbname = opanel_mail
query = SELECT destination FROM virtual_aliases va JOIN virtual_domains vd ON va.domain_id = vd.id WHERE CONCAT(va.source, '@', vd.name) = '%s'
EOSQL

# Start Postfix (creates /var/spool/postfix/private directory)
echo "Starting Postfix..."
postfix start

# Configure Dovecot (only override conf.d files, keep main dovecot.conf from package)
echo "Configuring Dovecot..."

cat > /etc/dovecot/conf.d/10-mail.conf <<'EOCONF'
mail_driver = maildir
mail_home = /var/vmail/%d/%n
mail_path = /var/vmail/%d/%n/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
last_valid_uid = 5000
EOCONF

cat > /etc/dovecot/conf.d/10-auth.conf <<'EOCONF'
auth_mechanisms = plain login
!include auth-passwdfile.conf.ext
EOCONF

cat > /etc/dovecot/conf.d/10-ssl.conf <<'EOCONF'
ssl = yes
ssl_server_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_server_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
EOCONF

cat > /etc/dovecot/conf.d/10-master.conf <<'EOCONF'
service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 0
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
    group = vmail
  }
  unix_listener /var/spool/postfix/private/dovecot-auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0660
    user = postfix
    group = postfix
  }
}
EOCONF

cat > /etc/dovecot/conf.d/auth-passwdfile.conf.ext <<'EOCONF'
passdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}

userdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}
EOCONF

# Create initial dovecot users file
cat > /etc/dovecot/users <<'EOUSERS'
# Auto-generated by OPanel
# Do not edit manually
EOUSERS
chown vmail:vmail /etc/dovecot/users
chmod 660 /etc/dovecot/users

# Start Dovecot
echo "Starting Dovecot..."
dovecot

# Start Rspamd
echo "Starting Rspamd..."
mkdir -p /var/lib/rspamd/dkim
chown _rspamd:_rspamd /var/lib/rspamd/dkim 2>/dev/null || true
rspamd --insecure

# Start PHP-FPM
echo "Starting PHP-FPM..."
php-fpm8.4 --allow-to-run-as-root -D

# Wait for PHP-FPM socket to be created
echo "Waiting for PHP-FPM socket..."
for i in $(seq 1 15); do
    if ls /run/php/php8.4-fpm-*.sock 2>/dev/null; then
        echo "PHP-FPM socket ready"
        break
    fi
    sleep 1
done

# Start Nginx
echo "Starting Nginx..."
nginx

# Start SSH
echo "Starting SSH..."
/usr/sbin/sshd

# Start OPanel
echo "Starting OPanel..."
exec /opt/opanel/bin/opaneld server --config /etc/opanel/config.yaml
